Add more control over autoloads
noctuid/general.el pull request #490
Opened 2021-08-10 23:58 UTC by VojtechStep

This PR adds the custom variable `general-use-package-emit-autoloads` to disable emitting autoloads, and the global and local keyword argument `:no-autoload`, which suppresses autoloading all commands from a form or just one of them, respectively.

I don't think this functionality can be implemented with the extensible keyword argument handling system, so it's baked-in into the use-package integration (but please correct me if I'm wrong).

Also, if you know more `cl-loop`-fu than I do, and you can come up with a way to write less ugly nested loops, please hit me up 😃.

Fixes #489

2021-08-12 21:54 UTC, noctuid requested changes
Great, thanks!

Left some comments with minor nitpicks.

One documentation change: Can you mention in the setting docstring and readme that `general-emit-autoloads` needs to be set at expansion time (i.e. `(eval-when-compile (setq general-emit-autoloads nil))` if the init is compiled).

The test setup is currently broken (at least on Emacs 28). I will try to get it fixed and add tests for this.

2021-08-12 21:54 UTC, noctuid commented on README.org
> +If generating autoloads for commands is not desirable, it can be disabled globally (with the ~general-use-package-emit-autoloads~ option), on a per-binding, or on a per-form basis. To skip generating
Use = for variables for consistency with the rest of the readme.

2021-08-12 21:54 UTC, noctuid commented on README.org
> +
Remove empty newline for consistency with the rest of the readme.

2021-08-12 21:54 UTC, noctuid commented on general.el
> +    (let* ((commands
Change to a `let` since you've removed the other binding.

2021-08-12 21:54 UTC, noctuid commented on general.el
> -                                 ;; remove extra quote
Keep the comments

2021-09-02 09:22 UTC, VojtechStep commented
@noctuid ping?

2021-09-04 16:31 UTC, noctuid commented
Sorry for the late response. I will try to look into the testing next week. Feel free to keep pinging me every week until this is merged in case I forget.

2021-09-04 17:10 UTC, noctuid commented
Since all tests still pass for previous Emacs versions, if I do not have time to write new ones soon, I will merge and do it later.

2021-09-17 21:43 UTC, VojtechStep commented
@noctuid ping

2021-09-18 15:32 UTC, noctuid commented
I've added tests and merged.

2021-09-18 15:32 UTC, closed without merging